# Generated by Django 3.0.5 on 2020-04-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mentee_skilss',
            new_name='mentee_skills',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mentor_skilss',
            new_name='mentor_skills',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to='portal.User'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='portal.User'),
        ),
    ]
