# Generated by Django 3.0.5 on 2020-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200413_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentee_Profile',
            new_name='MenteeProfile',
        ),
        migrations.RenameModel(
            old_name='Mentor_Profile',
            new_name='MentorProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_mentee',
            field=models.ManyToManyField(related_name='is_mentor_for', to='portal.User'),
        ),
    ]
