# Generated by Django 3.0.5 on 2020-04-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200413_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mentee_skills',
            field=models.ManyToManyField(blank=True, related_name='mentee_skills', to='portal.Skills'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mentor_mentee',
            field=models.ManyToManyField(blank=True, related_name='is_mentor_for', to='portal.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mentor_skills',
            field=models.ManyToManyField(blank=True, related_name='mentor_skills', to='portal.Skills'),
        ),
    ]
