# Generated by Django 3.0.5 on 2020-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200420_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='photo',
            field=models.ImageField(upload_to='profile_photo'),
        ),
    ]
