# Generated by Django 3.0.5 on 2020-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200413_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mentor_mentee',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_mentor_for', to='portal.User'),
        ),
    ]
