# Generated by Django 3.0.5 on 2020-04-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200413_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='portal.User')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='portal.User')),
            ],
            options={
                'unique_together': {('mentor', 'mentee')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='mentors',
            field=models.ManyToManyField(related_name='_user_mentors_+', through='portal.MentorRelationship', to='portal.User'),
        ),
    ]
