# Generated by Django 3.0.5 on 2020-04-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20200413_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mentors',
        ),
        migrations.AddField(
            model_name='user',
            name='mentorRelationship',
            field=models.ManyToManyField(related_name='_user_mentorRelationship_+', through='portal.MentorRelationship', to='portal.User'),
        ),
    ]
