# Generated by Django 3.0.5 on 2020-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_mentorprofile_fulldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=3000),
        ),
    ]
