# Generated by Django 3.0.5 on 2020-04-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20200414_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to='portal.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='portal.Client'),
            preserve_default=False,
        ),
    ]
