# Generated by Django 3.0.5 on 2020-04-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200415_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='totalUsersVotes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='totalVotes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
