# Generated by Django 3.0.5 on 2020-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200417_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
    ]
