# Generated by Django 3.0.5 on 2020-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20200418_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
    ]
