# Generated by Django 3.0.5 on 2020-04-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_mentorprofile_photo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='photo1',
        ),
    ]
