# Generated by Django 3.0.5 on 2020-04-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_remove_mentorprofile_photo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenteeProfile',
        ),
    ]
