# Generated by Django 3.0.5 on 2020-04-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_delete_menteeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mentee_skills',
        ),
    ]
