# Generated by Django 3.0.5 on 2020-04-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_remove_client_mentee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorrelationship',
            name='mentee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mentee', to='portal.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorrelationship',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='portal.Client'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mentorrelationship',
            unique_together={('mentor', 'mentee')},
        ),
        migrations.RemoveField(
            model_name='mentorrelationship',
            name='from_mentor',
        ),
        migrations.RemoveField(
            model_name='mentorrelationship',
            name='to_mentee',
        ),
    ]
