# Generated by Django 3.0.5 on 2020-04-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20200418_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='portal.Client'),
        ),
    ]
