# Generated by Django 3.0.5 on 2020-04-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20200418_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mentor_profile',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='portal.Client'),
            preserve_default=False,
        ),
    ]
