# Generated by Django 3.0.5 on 2020-04-19 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0028_auto_20200419_0930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Skills',
            new_name='User_Skill',
        ),
    ]
