# Generated by Django 3.0.5 on 2020-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20200419_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelationship',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
