# Generated by Django 3.0.5 on 2020-04-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0030_userrelationship_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
