# Generated by Django 3.0.5 on 2020-04-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_auto_20200419_1037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorrelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mentorrelationship',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='mentorrelationship',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='MentorRelationship',
        ),
    ]
