# Generated by Django 3.0.5 on 2020-04-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_comment_commentthread_commenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='userProfile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='portal.Person'),
            preserve_default=False,
        ),
    ]
