# Generated by Django 3.0.5 on 2020-04-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20200419_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorprofile',
            old_name='userProfile',
            new_name='user',
        ),
    ]
